# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0e624044d0b959d7e68c9a60c08a90cd96030327604b9d11b0b95b472ee435549f66c15e3046ec8eacddfed292db05e630581e0a051646f391acf99fec845b

test:
  secret_key_base: 79941e85ad11137c83d7460b52c30f3f4cd51de45a52c71ebaf72a93d4d28ede50c58bc7744d49a4baa59fa69d319ed23a325caca9c80937fe6c74b09ddd4ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
